config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :users

  root 'users#index'

end

app/models/match.rb
class Match < ActiveRecord::Base

  WINNING_RESULT = 10

  belongs_to :winner, class_name: 'User'
  belongs_to :looser, class_name: 'User'

  validates :winner, presence: true
  validates :looser, presence: true
  validates :date, presence: true
  validates :winning_result, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :loosing_result, presence: true, numericality: { greater_than: 0 }
  validate :loosing_result_smaller_than_winning

  private

  def loosing_result_smaller_than_winning
    if loosing_result && winning_result && loosing_result >= winning_result
      errors.add(:loosing_result, 'should be less than winning result')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :won_matches, class_name: Match, foreign_key: :winner_id, inverse_of: :winner
  has_many :lost_matches, class_name: Match, foreign_key: :looser_id, inverse_of: :looser

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    @match.winning_result = Match::WINNING_RESULT

    if @match.save
      redirect_to @match
    else
      render :new
    end
  end

  private

  def match_params
    params.require(:match).permit(:winner_id, :looser_id, :date, :loosing_result)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @statistics = generate_statistics_for_users(@users)
  end

  def show
    @user = User.includes(:won_matches, :lost_matches).find(params[:id])
    @statistics = MatchesStatisticsCalculator.generate_statistics(@user)
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end

  end

  def destroy
    #maybe shouldn't be removed just marked inactive?
    #TODO is needed? :P
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path

  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end

  def generate_statistics_for_users(users)
    statistics = Hash.new
    users.each do |user|
      statistics[user.id] = MatchesStatisticsCalculator.generate_statistics(user)
    end
    statistics
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoosballTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-brand">
      Foosball tracker
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/users/">Statistics</a></li>
      <li><a href="/matches/new">Add match</a></li>
      <li><a href="/users/new">Add user</a></li>
    </ul>
  </div>
</nav>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/matches/_form.erb
<%= form_for @match do |f| %>

    <% if @match.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@match.errors.count, "error") %> prohibited
            this match from being saved:
          </h2>
          <ul>
            <% @match.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :winner %><br>
      <%= f.collection_select(:winner_id, User.all, :id, :name, {:include_blank => true}, :class => 'form-control') %>
    </div>

    <div class="form-group">
      <%= f.label :looser %><br>
      <%= f.collection_select(:looser_id, User.all, :id, :name, {:include_blank => true}, :class => 'form-control') %>
    </div>

    <div class="form-group">
      <%= f.label :loosing_result %><br>
      <%= f.number_field :loosing_result, :class => 'form-control', :min => 0 %>
    </div>

    <div class="form-group">
      <%= f.label :date %><br>
      <%= f.text_field :date, :'data-provide' => 'datepicker', :'data-date-format' => 'yyyy-mm-dd', :class => 'form-control' %>
    </div>

    <p>
      <%= f.submit :class => 'btn btn-default', :type => 'submit' %>
    </p>

<% end %>

app/views/matches/new.erb
<div class="centered-container">
<h1> New match</h1>

<%=render 'form' %>
</div>

app/views/matches/show.erb
<div class="row">
  <div class="col-md-5 text-center">
    <h4><%= @match.winner.name %></h4>
    <img class="avatar-with-border" src= <%= @match.winner.avatar %> />
  </div>
  <div class="col-md-2">
    <div class="match-date-result text-center">
        <h3><%= @match.date.strftime("%Y-%m-%d") %></h3>

        <div class="match-result">
            <span class="text-green"><%= @match.winning_result %></span> - <span class="text-red"><%= @match.loosing_result %></span>
        </div>
    </div>
  </div>
  <div class="col-md-5 text-center">
    <h4><%= @match.looser.name %></h4>
    <img class="avatar-with-border" src= <%= @match.looser.avatar %> />
  </div>
</div>

app/views/users/_form.erb
<%= form_for @user do |f| %>

    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
          </h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :avatar %><br />
      <%= f.file_field :avatar %>
    </div>

    <%= f.submit :class => 'btn btn-default', :type => 'submit' %>


<% end %>

app/views/users/_matches_table.erb
<table class="table table-striped">
    <tbody>
        <% matches.each do |match| %>
            <tr>
                <td><%= match.date.strftime("%Y-%m-%d") %></td>
                <td>
                  <%= link_to match.winner.name, user_path(match.winner) %>
                  vs
                  <%= link_to match.looser.name, user_path(match.looser) %>
                </td>
                <td>
                  <span class="text-green"><%= match.winning_result %></span>
                  -
                  <span class="text-red"><%= match.loosing_result %></span>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/edit.erb
<h1>Editing user</h1>

<%=render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.erb
<div id="statistics-header">
  <h2>Users' statistics</h2>
</div>
<div id="new-user-button">
  <%= link_to 'New user', new_user_path, :class => 'btn btn-primary' %>
</div>
<table data-toggle="table" data-sort-name="factor" data-sort-order="desc">
  <thead>
    <th>Avatar</th>
    <th data-sortable="true">Name</th>
    <th data-sortable="true">Played</th>
    <th data-sortable="true">Won</th>
    <th data-sortable="true">Lost</th>
    <th data-sortable="true">Sum of points</th>
    <th data-sortable="true" data-field="factor">Average result factor</th>
  </thead>
  <tbody>
      <% @users.each do |user| %>
          <tr>
            <td class="users-statistics-avatar">
              <%= link_to image_tag(user.avatar.thumb.url, :border => 0), user_path(user) %>
            </td>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= @statistics[user.id].played %></td>
            <td><%= @statistics[user.id].won %></td>
            <td><%= @statistics[user.id].lost %></td>
            <td><%= @statistics[user.id].sum_of_points %></td>
            <td><%= @statistics[user.id].avg_result %></td>
          </tr>
      <% end %>
  </tbody>
</table>

app/views/users/new.erb
<div class="centered-container">
  <h1>New User</h1>

  <%= render 'form' %>
</div>

app/views/users/show.erb
<div class="centered-container">
  <%= image_tag @user.avatar, class: 'avatar-big avatar-with-border' %>
  <div class="user-inf">
    <h3 class="user-name-header"><%= @user.name %></h3>

    <table class="user-statistics-table">
      <tr>
        <th>Played matches</th>
        <td><%= @statistics.played %></td>
      </tr>
      <tr>
        <th class="text-green">Won matches</th>
        <td><%= @statistics.won %></td>
      </tr>
      <tr>
        <th class="text-red">Lost matches</th>
        <td><%= @statistics.lost %></td>
      </tr>
      <tr>
        <th>Avg result factor</th>
        <td><%= @statistics.avg_result %></td>
      </tr>
    </table>
  </div>
</div>

<div class="user-matches-lists row">
  <div class="col-md-6">
    <div class="user-matches-list-header bg-red text-center">Lost matches</div>
    <%= render 'matches_table', matches: @user.lost_matches, side: :loosing  %>
  </div>
  <div class="col-md-6">
    <div class="user-matches-list-header bg-green text-center">Won matches</div>
    <%= render 'matches_table', matches: @user.won_matches, side: :winning  %>
  </div>
</div>